name: ${DOCKER_USER_NAME}
services:
  nlpx:
    container_name: "nlpx"
    user: ${DOCKER_USER_ID}:${DOCKER_GROUP_ID}
    userns_mode: "host"
    build:
      context: "./docker/Dockerfile"
      tags:
        - "nlpx:0.3"
      platforms:
        - "linux/amd64"
      args:
        USER_NAME: ${SERVICE_USER_NAME}
    image: nlpx:0.3
    pull_policy: build
    command: bash sh/docker_run.sh $ARGS_FILE
    working_dir: /explore
    volumes:
      - type: bind
        source: /home/${DOCKER_USER_NAME}/.cache
        target: /home/${SERVICE_USER_NAME}/.cache
      - type: bind
        source: /home/${DOCKER_USER_NAME}/ray_results
        target: /home/${SERVICE_USER_NAME}/ray_results
      - type: bind
        source: /home/docker-1024/docker/bind/nlpx/cache
        target: /explore/.cache
      - type: bind
        source: /home/docker-1024/docker/bind/nlpx/output
        target: /explore/output
      - type: bind
        source: /home/docker-1024/docker/bind/nlpx/tmp
        target: /explore/tmp
      - type: bind
        source: /home/docker-1024/docker/bind/nlpx/storage
        target: /explore/storage
    network_mode: "host"
    dns:
      - 172.23.4.46
      - 172.23.3.11
      - 8.8.8.8

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ulimits:
      memlock: -1
      stack: 67108864 
    tty: true
    stdin_open: true

  nlpx_env:
    container_name: "nlpx-env"
    build:
      context: "."
      tags:
        - "nlpx_env:0.3"
      platforms:
        - "linux/amd64"
      dockerfile: "./docker/Dockerfile-env"
      args:
        USER_ID: ${DOCKER_USER_ID}
        GROUP_ID: ${DOCKER_GROUP_ID}
        USER_NAME: ${SERVICE_USER_NAME}

    image: nlpx_env:0.3
    command: echo "Finsh set up environment!"
    pull_policy: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    ulimits:
      memlock: -1
      stack: 67108864
    tty: true
    stdin_open: true