# syntax = docker/dockerfile:1
FROM python:3.10 AS base
SHELL [ "/bin/bash", "-c"]
# RUN perl -p -i.bak -e 's%(deb(?:-src|)\s+)https?://(?!archive\.canonical\.com|security\.ubuntu\.com)[^\s]+%$1http://ftp.jaist.ac.jp/pub/Linux/ubuntu/%' /etc/apt/sources.list
RUN apt-get update -y
RUN apt-get install -y iputils-ping
RUN apt-get install -y traceroute
RUN apt-get install -y net-tools
RUN apt-get install -y dnsutils
RUN apt-get install -y vim
RUN apt-get install -y wget
WORKDIR /explore

FROM base AS environment
ENV ENV_FILE="./environment/pip_linux_amd64.txt"
COPY $ENV_FILE $ENV_FILE
RUN pip install -r  $ENV_FILE

# additional pip packages
RUN pip install pytorch-metric-learning
RUN pip install tensorboard
RUN pip install tensorboardX

# add non-root user infomation

ARG USER_ID
ARG GROUP_ID
ARG USER_NAME
RUN if [ ${USER_ID:-0} -ne 0 ] && [ ${GROUP_ID:-0} -ne 0 ]; then \
    	if grep ${USER_NAME} /etc/passwd; then deluser --remove-all-files ${USER_NAME}  && delgroup ${USER_NAME} ;  fi &&\
    	adduser --disabled-password --uid ${USER_ID} ${USER_NAME}  \
    ;fi